# Generated by Django 3.2.7 on 2021-10-10 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parents.parent')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.student')),
            ],
            options={
                'unique_together': {('student_id', 'parent_id')},
            },
        ),
    ]
